parameters:
  DATABASE_URL: 'mysql://root:@127:0:0:1:3306/sortir_bdd?'
  MAILER_DSN: 'smtp://cbb1c50c9f27ee:d6d664840766e2@sandbox.smtp.mailtrap.io:2525?encryption=tls&auth_mode=login'
  MESSENGER_TRANSPORT_DSN: 'doctrine://default?auto_setup=0'